#include "Compiler.h"

#include <cstdlib>
#include <map>
#include <sstream>
#include <stdexcept>

namespace {

constexpr int kTapeSize = 30000;

int wrapByte(int value) { return value & 0xFF; }

std::string position(const Token& t) {
    return std::to_string(t.line) + ":" + std::to_string(t.column);
}

// ---------------------------------------------------------------- optimizer

bool isNoop(const Instr& i) {
    return (i.op == Op::Add && wrapByte(i.arg) == 0) || (i.op == Op::Move && i.arg == 0);
}

// Appends while merging with the previous instruction where possible.
void append(Program& out, Instr next) {
    if (isNoop(next)) return;
    if (out.empty()) {
        out.push_back(next);
        return;
    }

    const Instr prev = out.back();
    const bool sameAccumulating = prev.op == next.op && (next.op == Op::Add || next.op == Op::Move);

    if (sameAccumulating) {
        out.pop_back();
        append(out, {next.op, prev.arg + next.arg});
    } else if (prev.op == Op::Set && next.op == Op::Add) {
        out.back().arg = wrapByte(prev.arg + next.arg);
    } else if (next.op == Op::Set && (prev.op == Op::Add || prev.op == Op::Set)) {
        out.pop_back();
        append(out, next);
    } else {
        out.push_back(next);
    }
}

// Index of the LoopEnd closing the loop at `begin` if the body is only Add/Move, else npos.
size_t simpleLoopEnd(const Program& p, size_t begin) {
    for (size_t i = begin + 1; i < p.size(); ++i) {
        if (p[i].op == Op::LoopEnd) return i;
        if (p[i].op != Op::Add && p[i].op != Op::Move) break;
    }
    return std::string::npos;
}

// Replaces [-], [+] and balanced copy/multiply loops such as [->+++<].
// Returns false (and emits nothing) if the loop does not match.
bool foldSimpleLoop(const Program& p, size_t begin, size_t end, Program& out) {
    std::map<int, int> deltaAt;  // offset from the loop's cell -> net change
    int offset = 0;
    for (size_t i = begin + 1; i < end; ++i) {
        if (p[i].op == Op::Add) deltaAt[offset] += p[i].arg;
        else offset += p[i].arg;
    }
    if (offset != 0) return false;

    const int origin = wrapByte(deltaAt[0]);
    deltaAt.erase(0);

    const bool terminatesAlone = deltaAt.empty() && (origin & 1);
    const bool decrementsByOne = origin == 0xFF;
    if (!terminatesAlone && !decrementsByOne) return false;

    if (decrementsByOne) {
        for (const auto& [off, delta] : deltaAt) {
            if (wrapByte(delta) != 0) out.push_back({Op::MulAdd, off, wrapByte(delta)});
        }
    }
    out.push_back({Op::Set, 0});
    return true;
}

Program foldLoops(const Program& in) {
    Program out;
    for (size_t i = 0; i < in.size(); ++i) {
        if (in[i].op == Op::LoopBegin) {
            const size_t end = simpleLoopEnd(in, i);
            if (end != std::string::npos && foldSimpleLoop(in, i, end, out)) {
                i = end;
                continue;
            }
        }
        out.push_back(in[i]);
    }
    return out;
}

Program mergeInstructions(const Program& in) {
    Program out;
    for (const Instr& i : in) append(out, i);
    return out;
}

// ------------------------------------------------------------- MASM backend

class MasmEmitter {
public:
    explicit MasmEmitter(const MasmOptions& options) : checked_(options.boundsCheck) {}

    std::string run(const Program& program) {
        header();
        for (const Instr& i : program) instruction(i);
        footer();
        return out_.str();
    }

private:
    void header() {
        out_ << "; Generated by bfc\n"
                "extern GetStdHandle : proc\n"
                "extern ReadFile     : proc\n"
                "extern WriteFile    : proc\n"
                "extern ExitProcess  : proc\n\n"
                ".data?\n"
                "tape    BYTE " << kTapeSize << " dup(?)\n"
                "ioCount DWORD ?\n\n"
                ".code\n"
                "main PROC\n"
                "    sub  rsp, 56              ; shadow space + 5th arg, 16-byte aligned\n"
                "    mov  ecx, -11\n"
                "    call GetStdHandle\n"
                "    mov  r12, rax             ; stdout\n"
                "    mov  ecx, -10\n"
                "    call GetStdHandle\n"
                "    mov  r13, rax             ; stdin\n"
                "    lea  rbx, tape            ; data pointer\n"
                "    lea  r14, tape            ; tape start\n"
                "    lea  r15, [r14 + " << kTapeSize << "] ; tape end\n";
    }

    void footer() {
        out_ << "    xor  ecx, ecx\n"
                "    call ExitProcess\n";
        if (checked_) {
            out_ << "bf_oob:\n"
                    "    mov  ecx, 1\n"
                    "    call ExitProcess\n";
        }
        out_ << "main ENDP\nEND\n";
    }

    void instruction(const Instr& i) {
        switch (i.op) {
            case Op::Add: out_ << "    add  byte ptr [rbx], " << wrapByte(i.arg) << "\n"; break;
            case Op::Set: out_ << "    mov  byte ptr [rbx], " << wrapByte(i.arg) << "\n"; break;
            case Op::Move:
                out_ << "    add  rbx, " << i.arg << "\n";
                checkBounds("rbx");
                break;
            case Op::MulAdd: mulAdd(i); break;
            case Op::Out: io("WriteFile", "r12", false); break;
            case Op::In: io("ReadFile", "r13", true); break;
            case Op::LoopBegin: loopBegin(); break;
            case Op::LoopEnd: loopEnd(); break;
        }
    }

    void mulAdd(const Instr& i) {
        out_ << "    movzx eax, byte ptr [rbx]\n";
        if (i.factor != 1) out_ << "    imul eax, eax, " << i.factor << "\n";
        out_ << "    lea  rdx, [rbx" << (i.arg < 0 ? "-" : "+") << std::abs(i.arg) << "]\n";
        checkBounds("rdx");
        out_ << "    add  byte ptr [rdx], al\n";
    }

    void io(const char* api, const char* handleReg, bool zeroFirst) {
        if (zeroFirst) out_ << "    mov  byte ptr [rbx], 0    ; EOF -> 0\n";
        out_ << "    mov  rcx, " << handleReg << "\n"
                "    mov  rdx, rbx\n"
                "    mov  r8d, 1\n"
                "    lea  r9, ioCount\n"
                "    mov  qword ptr [rsp+32], 0\n"
                "    call " << api << "\n";
    }

    void loopBegin() {
        open_.push_back(labelCount_);
        out_ << "L" << labelCount_ << "_begin:\n"
                "    cmp  byte ptr [rbx], 0\n"
                "    je   L" << labelCount_ << "_end\n";
        ++labelCount_;
    }

    void loopEnd() {
        const int id = open_.back();
        open_.pop_back();
        out_ << "    jmp  L" << id << "_begin\n"
                "L" << id << "_end:\n";
    }

    void checkBounds(const char* reg) {
        if (!checked_) return;
        out_ << "    cmp  " << reg << ", r14\n"
                "    jb   bf_oob\n"
                "    cmp  " << reg << ", r15\n"
                "    jae  bf_oob\n";
    }

    std::ostringstream out_;
    std::vector<int> open_;
    int labelCount_ = 0;
    bool checked_;
};

// ------------------------------------------------------------- C++ backend

class CppEmitter {
public:
    std::string run(const Program& program) {
        out_ << "#include <cstdio>\n\n"
                "int main() {\n"
                "    unsigned char tape[" << kTapeSize << "]{};\n"
                "    unsigned char* p = tape;\n";
        for (const Instr& i : program) instruction(i);
        out_ << "}\n";
        return out_.str();
    }

private:
    std::string indent() const { return std::string(depth_ * 4, ' '); }

    void instruction(const Instr& i) {
        if (i.op == Op::LoopEnd) --depth_;
        out_ << indent();
        switch (i.op) {
            case Op::Add: out_ << "*p += " << wrapByte(i.arg) << ";\n"; break;
            case Op::Set: out_ << "*p = " << wrapByte(i.arg) << ";\n"; break;
            case Op::Move: out_ << "p += " << i.arg << ";\n"; break;
            case Op::MulAdd: out_ << "p[" << i.arg << "] += *p * " << i.factor << ";\n"; break;
            case Op::Out: out_ << "std::putchar(*p);\n"; break;
            case Op::In: out_ << "{ int c = std::getchar(); *p = c == EOF ? 0 : c; }\n"; break;
            case Op::LoopBegin: out_ << "while (*p) {\n"; break;
            case Op::LoopEnd: out_ << "}\n"; break;
        }
        if (i.op == Op::LoopBegin) ++depth_;
    }

    std::ostringstream out_;
    int depth_ = 1;
};

}  // namespace

// --------------------------------------------------------------- public API

Program parse(const std::vector<Token>& tokens) {
    Program prog;
    std::vector<const Token*> open;

    auto fold = [&](Op op, int delta) {
        if (!prog.empty() && prog.back().op == op) prog.back().arg += delta;
        else prog.push_back({op, delta});
    };

    for (const Token& t : tokens) {
        switch (t.kind) {
            case TokenKind::Inc: fold(Op::Add, 1); break;
            case TokenKind::Dec: fold(Op::Add, -1); break;
            case TokenKind::Right: fold(Op::Move, 1); break;
            case TokenKind::Left: fold(Op::Move, -1); break;
            case TokenKind::Out: prog.push_back({Op::Out}); break;
            case TokenKind::In: prog.push_back({Op::In}); break;
            case TokenKind::LoopBegin:
                open.push_back(&t);
                prog.push_back({Op::LoopBegin});
                break;
            case TokenKind::LoopEnd:
                if (open.empty()) throw std::runtime_error("unmatched ']' at " + position(t));
                open.pop_back();
                prog.push_back({Op::LoopEnd});
                break;
        }
    }
    if (!open.empty()) throw std::runtime_error("unmatched '[' at " + position(*open.back()));
    return prog;
}

Program optimize(const Program& program) {
    return mergeInstructions(foldLoops(mergeInstructions(program)));
}

std::string emitMasm(const Program& program, const MasmOptions& options) {
    return MasmEmitter(options).run(program);
}

std::string emitCpp(const Program& program) { return CppEmitter().run(program); }
